### PR TITLE
Adding .gitignore and deleting .DS_Store

### PR DESCRIPTION
**Pull request by l1x**
Just minor adjustments

### CODE REVIEW

**Comment by heitorlessa** [comment]
hey @l1x thanks for that ;-)

Could you do me a favour and update this PR with other OSes too (Windows, Linux)?

I usually generate from here: gitignore.io

**Review by heitorlessa — CHANGES_REQUESTED** [review]
Updates .gitignore with other OSes too

**Comment by l1x** [comment]
Hi @heitorlessa,

Which language from gitignore would you like to see in the pull request?

Would this work? https://www.gitignore.io/api/python

**Comment by heitorlessa** [comment]
What about this one that contains only OSes and not a language?

* https://www.gitignore.io/api/osx%2Clinux%2Cwindows

I checked the source code just to be sure and they were all .yaml files so I think we don't need a language and OS will suffice.

Thoughts?

**Review by heitorlessa — APPROVED** [review]

**Comment by heitorlessa** [comment]
Awesome @l1x ! Just approved changes and merging this now. 

Thank you very much for this contribution!

**Pull request merged**
